[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "language-tool-python>=2.8.2",
    "pandas>=2.2.3",
    "pydub>=0.25.1",
    "speechrecognition>=3.14.1",
]
